name: Deploy Azure Function

on:
  push:
    branches: [ master ]
    paths:
      - 'azure-functions/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: |
        cd azure-functions/SendGridEmailFunction
        npm install
    
    - name: Deploy Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: kh-email-function
        package: azure-functions/SendGridEmailFunction
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }} 